/**
 * Token build: DTCG JSON in tokens/ -> src/styles/tokens.css + src/tokens/tokens.ts.
 *
 *   node scripts/build-tokens.ts           write the generated files
 *   node scripts/build-tokens.ts --check   fail if the committed files are stale
 *
 * Style Dictionary parses the source, merges files and validates every alias
 * (a broken reference throws). The formats below own the output: aliases are
 * emitted as var() references so the tier chain stays visible in the CSS, and
 * colours with a dark mode value become light-dark().
 */
import { mkdtempSync, readFileSync, rmSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, relative, resolve } from 'node:path';
import StyleDictionary from 'style-dictionary';
import type { Dictionary, TransformedToken } from 'style-dictionary/types';

const root = resolve(import.meta.dirname, '..');
const MODES = 'starter.modes';
const OUTPUTS = [
  { destination: 'tokens.css', format: 'starter/css', target: 'src/styles/tokens.css' },
  { destination: 'tokens.ts', format: 'starter/ts', target: 'src/tokens/tokens.ts' },
] as const;
const HEADER = 'Generated by scripts/build-tokens.ts from the DTCG source in tokens/. Do not edit by hand.';

type Tier = 'primitive' | 'semantic' | 'component';

const tierOf = (token: TransformedToken): Tier => {
  const tier = relative(join(root, 'tokens'), resolve(root, token.filePath)).split(/[\\/]/)[0];
  if (tier === 'primitive' || tier === 'semantic' || tier === 'component') return tier;
  throw new Error(`Token ${token.path.join('.')} is outside tokens/{primitive,semantic,component}/`);
};

const cssName = (path: readonly string[]): string => {
  for (const key of path) {
    if (!/^[a-z0-9]+(-[a-z0-9]+)*$/.test(key)) {
      throw new Error(`Token key "${key}" in ${path.join('.')} must be lowercase kebab-case`);
    }
  }
  return `--${path.join('-')}`;
};

const ALIAS = /^\{([^{}]+)\}$/;
const refToVar = (ref: string): string => `var(${cssName(ref.split('.'))})`;

interface Dimension { value: number; unit: string }
const isDimension = (v: unknown): v is Dimension =>
  typeof v === 'object' && v !== null && 'value' in v && 'unit' in v;

/** Serialise one DTCG value (possibly an alias, possibly composite) to CSS. */
const toCss = (value: unknown, type: string | undefined): string => {
  if (typeof value === 'string') {
    const alias = ALIAS.exec(value);
    if (alias?.[1]) return refToVar(alias[1]);
    if (value.includes('{')) throw new Error(`Partial alias not supported: ${value}`);
  }
  switch (type) {
    case 'dimension':
    case 'duration':
      if (isDimension(value)) return value.value === 0 && type === 'dimension' ? '0' : `${value.value}${value.unit}`;
      return String(value);
    case 'cubicBezier':
      if (Array.isArray(value)) return `cubic-bezier(${value.join(', ')})`;
      break;
    case 'fontFamily': {
      const families = Array.isArray(value) ? value : [value];
      return families.map((f) => (/\s/.test(String(f)) ? `"${String(f)}"` : String(f))).join(', ');
    }
    case 'typography': {
      const t = value as Record<string, unknown>;
      return `${toCss(t.fontWeight, 'fontWeight')} ${toCss(t.fontSize, 'dimension')}/${toCss(t.lineHeight, 'number')} ${toCss(t.fontFamily, 'fontFamily')}`;
    }
    case 'shadow': {
      const layers = Array.isArray(value) ? value : [value];
      return layers
        .map((layer: Record<string, unknown>) =>
          [
            layer.inset === true ? 'inset' : '',
            toCss(layer.offsetX, 'dimension'),
            toCss(layer.offsetY, 'dimension'),
            toCss(layer.blur, 'dimension'),
            toCss(layer.spread, 'dimension'),
            toCss(layer.color, 'color'),
          ]
            .filter(Boolean)
            .join(' '),
        )
        .join(', ');
    }
    default:
      break;
  }
  if (typeof value === 'string' || typeof value === 'number') return String(value);
  throw new Error(`Cannot serialise ${type ?? 'untyped'} value ${JSON.stringify(value)}`);
};

const modesOf = (token: TransformedToken): Record<string, unknown> =>
  ((token.original.$extensions as Record<string, unknown> | undefined)?.[MODES] as Record<string, unknown> | undefined) ?? {};

const lightValue = (token: TransformedToken): string => toCss(token.original.$value, token.$type);

const declaration = (token: TransformedToken): string => {
  const { dark } = modesOf(token);
  const light = lightValue(token);
  if (dark === undefined) return light;
  if (token.$type !== 'color') throw new Error(`${token.path.join('.')}: dark mode is only supported on colours`);
  return `light-dark(${light}, ${toCss(dark, 'color')})`;
};

const byTier = (dictionary: Dictionary, tier: Tier) => dictionary.allTokens.filter((t) => tierOf(t) === tier);

StyleDictionary.registerTransform({
  name: 'starter/name',
  type: 'name',
  transform: (token) => cssName(token.path).slice(2),
});

StyleDictionary.registerFormat({
  name: 'starter/css',
  format: ({ dictionary }) => {
    const lines: string[] = [`/* ${HEADER} */`, '@layer tokens {', '  :root {'];
    const seen = new Set<string>();
    for (const tier of ['primitive', 'semantic', 'component'] as const) {
      lines.push(`    /* ${tier} */`);
      for (const token of byTier(dictionary, tier)) {
        const name = cssName(token.path);
        if (seen.has(name)) throw new Error(`Duplicate CSS custom property ${name}`);
        seen.add(name);
        lines.push(`    ${name}: ${declaration(token)};`);
      }
    }
    lines.push('  }');
    const reduced = dictionary.allTokens.filter((t) => modesOf(t)['reduced-motion'] !== undefined);
    if (reduced.length > 0) {
      lines.push('', '  @media (prefers-reduced-motion: reduce) {', '    :root {');
      for (const token of reduced) {
        lines.push(`      ${cssName(token.path)}: ${toCss(modesOf(token)['reduced-motion'], token.$type)};`);
      }
      lines.push('    }', '  }');
    }
    lines.push('}', '');
    return lines.join('\n');
  },
});

/** Nested object of var() references for the semantic and component tiers. */
StyleDictionary.registerFormat({
  name: 'starter/ts',
  format: ({ dictionary }) => {
    const tree: Record<string, unknown> = {};
    for (const token of dictionary.allTokens.filter((t) => tierOf(t) !== 'primitive')) {
      let node = tree;
      token.path.slice(0, -1).forEach((key) => {
        node[key] ??= {};
        node = node[key] as Record<string, unknown>;
      });
      node[token.path.at(-1) as string] = `var(${cssName(token.path)})`;
    }
    return [
      `// ${HEADER}`,
      '// Semantic and component tokens as var() references. Primitives are deliberately absent:',
      '// nothing outside the token source should read them.',
      `export const vars = ${JSON.stringify(tree, null, 2)} as const;`,
      '',
      'export type GapToken = keyof typeof vars.space.gap;',
      'export type InsetToken = keyof typeof vars.space.inset;',
      'export type ContentWidthToken = keyof typeof vars.size.content;',
      'export type SidebarWidthToken = keyof typeof vars.size.sidebar;',
      'export type GridItemToken = keyof typeof vars.size[\'grid-item\'];',
      'export type ScrollRegionToken = keyof typeof vars.size[\'scroll-region\'];',
      'export type RatioToken = keyof typeof vars.ratio;',
      '',
    ].join('\n');
  },
});

const build = async (outDir: string) => {
  const sd = new StyleDictionary({
    source: [join(root, 'tokens/**/*.json')],
    usesDtcg: true,
    log: { verbosity: 'silent', warnings: 'error', errors: { brokenReferences: 'throw' } },
    platforms: {
      web: {
        transforms: ['starter/name'],
        buildPath: `${outDir}/`,
        files: OUTPUTS.map(({ destination, format }) => ({ destination, format })),
      },
    },
  });
  await sd.buildAllPlatforms();
};

const check = process.argv.includes('--check');
const tmp = mkdtempSync(join(tmpdir(), 'tokens-'));
try {
  await build(tmp);
  const stale: string[] = [];
  for (const { destination, target } of OUTPUTS) {
    const fresh = readFileSync(join(tmp, destination), 'utf8');
    const path = join(root, target);
    if (check) {
      if (!existsSync(path) || readFileSync(path, 'utf8') !== fresh) stale.push(target);
    } else {
      mkdirSync(dirname(path), { recursive: true });
      writeFileSync(path, fresh);
      console.log(`tokens: wrote ${target}`);
    }
  }
  if (stale.length > 0) {
    console.error(`tokens: generated files are out of date: ${stale.join(', ')}\nRun "npm run tokens" and commit the result.`);
    process.exitCode = 1;
  } else if (check) {
    console.log('tokens: generated files are up to date');
  }
} finally {
  rmSync(tmp, { recursive: true, force: true });
}
