/** @jsxRuntime classic */
/**
 * The "Tokens" addon panel: for the current story's component, primitive or layout, every token
 * it reads (itself or through the parts it composes), with the token's tier, alias chain and
 * light and dark values.
 *
 * Everything comes from src/tokens/token-usage.json, generated by scripts/token-usage.ts from the
 * stylesheets, TSX and token source (npm run tokens; a unit test fails when it is stale). This
 * file only renders it: the manager bundle cannot read the token source itself.
 *
 * Classic JSX (the pragma above): the manager provides React as a global, and the automatic
 * runtime would bundle the repo's own react/jsx-runtime, which fails against the manager's React.
 */
import React, { useState, type CSSProperties } from 'react';
import { AddonPanel } from 'storybook/internal/components';
import { addons, types, useStorybookApi, useStorybookState } from 'storybook/manager-api';
import { useTheme } from 'storybook/theming';
import type { TokenInfo, TokenUsage, UnitUsage } from '../scripts/checks/token-usage';
import usageJson from '../src/tokens/token-usage.json';

const usage = usageJson as unknown as TokenUsage;
const ADDON_ID = 'starter/tokens';
const PANEL_ID = `${ADDON_ID}/panel`;

/** Story titles end in the unit's folder name: "Components/Button" → Button. */
const unitFor = (title: string | undefined): [string, UnitUsage] | undefined => {
  const name = title?.split('/').at(-1);
  const unit = name ? usage.units[name] : undefined;
  return name && unit ? [name, unit] : undefined;
};

function Value({ info, value }: { info: TokenInfo; value: string }) {
  const theme = useTheme();
  const swatch: CSSProperties = {
    display: 'inline-block',
    inlineSize: 14,
    blockSize: 14,
    marginInlineEnd: 6,
    verticalAlign: 'middle',
    borderRadius: 3,
    border: `1px solid ${theme.appBorderColor}`,
    background: value,
  };
  return (
    <span style={{ whiteSpace: 'nowrap' }}>
      {info.type === 'color' ? <span style={swatch} aria-hidden="true" /> : null}
      <code>{value}</code>
    </span>
  );
}

function TokensPanel() {
  const api = useStorybookApi();
  const state = useStorybookState();
  const theme = useTheme();
  const [filter, setFilter] = useState('');
  const story = state.storyId ? api.getCurrentStoryData() : undefined;
  const found = unitFor(story?.title);

  const pad: CSSProperties = { padding: '12px 16px', fontSize: 13, lineHeight: 1.5 };
  if (!found) {
    return (
      <div style={pad}>
        <p style={{ margin: 0 }}>
          No token map for <strong>{story?.title ?? 'this story'}</strong>. The Tokens panel covers components, primitives and layouts
          (src/tokens/token-usage.json).
        </p>
      </div>
    );
  }

  const [name, unit] = found;
  const query = filter.trim().toLowerCase();
  const rows = unit.tokens.filter(({ token }) => !query || token.includes(query) || (usage.tokens[token]?.cssVar ?? '').includes(query));
  const own = unit.tokens.filter((t) => t.readBy.some((r) => r.unit === name)).length;
  const cell: CSSProperties = { padding: '6px 8px', borderBlockEnd: `1px solid ${theme.appBorderColor}`, verticalAlign: 'top', textAlign: 'start' };
  const muted: CSSProperties = { color: theme.textMutedColor };

  return (
    <div style={pad}>
      <div style={{ display: 'flex', flexWrap: 'wrap', gap: 12, alignItems: 'baseline', marginBlockEnd: 8 }}>
        <strong>
          {name} reads {unit.tokens.length} tokens
        </strong>
        <span style={muted}>
          {own} in its own {unit.kind}
          {unit.composesAll.length ? `, the rest through ${unit.composesAll.join(', ')}` : ''}. Content passed in by the caller is not
          included.
        </span>
        <label style={{ marginInlineStart: 'auto' }}>
          <span style={{ marginInlineEnd: 6 }}>Filter</span>
          <input value={filter} onChange={(e) => setFilter(e.target.value)} placeholder="color, space.gap…" />
        </label>
      </div>
      <table style={{ borderCollapse: 'collapse', inlineSize: '100%' }}>
        <thead>
          <tr>
            {['Token', 'Tier', 'Chain', 'Light', 'Dark', 'Read by'].map((h) => (
              <th key={h} scope="col" style={{ ...cell, fontWeight: 700 }}>
                {h}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {rows.map(({ token, readBy }) => {
            const info = usage.tokens[token];
            if (!info) return null;
            const dark = info.modes.dark;
            return (
              <tr key={token}>
                <th scope="row" style={{ ...cell, fontWeight: 400 }}>
                  <code>{info.cssVar}</code>
                  {info.description ? <div style={muted}>{info.description}</div> : null}
                </th>
                <td style={cell}>{info.tier}</td>
                <td style={cell}>
                  <code>{info.chain.join(' → ')}</code>
                  {dark && dark.chain.join() !== info.chain.join() ? (
                    <div style={muted}>
                      dark: <code>{dark.chain.join(' → ')}</code>
                    </div>
                  ) : null}
                  {Object.entries(info.modes)
                    .filter(([mode]) => mode !== 'dark')
                    .map(([mode, v]) => (
                      <div key={mode} style={muted}>
                        {mode}: <code>{v.value}</code>
                      </div>
                    ))}
                </td>
                <td style={cell}>
                  <Value info={info} value={info.value} />
                </td>
                <td style={cell}>{dark ? <Value info={info} value={dark.value} /> : <span style={muted}>same</span>}</td>
                <td style={cell}>
                  {readBy.map((r) => (
                    <div key={`${r.unit}-${r.how}`}>
                      {r.unit}
                      <span style={muted}> ({r.how === 'prop' ? 'prop' : 'CSS'})</span>
                    </div>
                  ))}
                </td>
              </tr>
            );
          })}
        </tbody>
      </table>
    </div>
  );
}

addons.register(ADDON_ID, () => {
  addons.add(PANEL_ID, {
    type: types.PANEL,
    title: 'Tokens',
    match: ({ viewMode }) => viewMode === 'story',
    render: ({ active }) => (
      <AddonPanel active={Boolean(active)}>
        <TokensPanel />
      </AddonPanel>
    ),
  });
});
