// Generated by scripts/build-tokens.ts from the DTCG source in tokens/. Do not edit by hand.
/**
 * Semantic and component tokens as var() references, for inline custom properties in system code
 * (vars.space.gap.md). Primitives are deliberately absent: nothing outside the token source reads them.
 */
export const vars = {
  "button": {
    "primary": {
      "bg": "var(--button-primary-bg)",
      "bg-hover": "var(--button-primary-bg-hover)",
      "fg": "var(--button-primary-fg)"
    },
    "secondary": {
      "bg": "var(--button-secondary-bg)",
      "bg-hover": "var(--button-secondary-bg-hover)",
      "fg": "var(--button-secondary-fg)",
      "border": "var(--button-secondary-border)"
    },
    "ghost": {
      "bg-hover": "var(--button-ghost-bg-hover)",
      "fg": "var(--button-ghost-fg)"
    },
    "danger": {
      "bg": "var(--button-danger-bg)",
      "bg-hover": "var(--button-danger-bg-hover)",
      "fg": "var(--button-danger-fg)"
    }
  },
  "color": {
    "chart": {
      "categorical": {
        "1": "var(--color-chart-categorical-1)",
        "2": "var(--color-chart-categorical-2)",
        "3": "var(--color-chart-categorical-3)",
        "4": "var(--color-chart-categorical-4)",
        "5": "var(--color-chart-categorical-5)",
        "6": "var(--color-chart-categorical-6)",
        "7": "var(--color-chart-categorical-7)",
        "8": "var(--color-chart-categorical-8)"
      },
      "sequential": {
        "1": "var(--color-chart-sequential-1)",
        "2": "var(--color-chart-sequential-2)",
        "3": "var(--color-chart-sequential-3)",
        "4": "var(--color-chart-sequential-4)",
        "5": "var(--color-chart-sequential-5)"
      },
      "diverging": {
        "below-2": "var(--color-chart-diverging-below-2)",
        "below-1": "var(--color-chart-diverging-below-1)",
        "midpoint": "var(--color-chart-diverging-midpoint)",
        "above-1": "var(--color-chart-diverging-above-1)",
        "above-2": "var(--color-chart-diverging-above-2)"
      }
    },
    "bg": {
      "canvas": "var(--color-bg-canvas)",
      "surface": "var(--color-bg-surface)",
      "subtle": "var(--color-bg-subtle)",
      "elevated": "var(--color-bg-elevated)",
      "hover": "var(--color-bg-hover)",
      "selected": "var(--color-bg-selected)",
      "inverse": "var(--color-bg-inverse)",
      "scrim": "var(--color-bg-scrim)",
      "placeholder": "var(--color-bg-placeholder)"
    },
    "fg": {
      "default": "var(--color-fg-default)",
      "muted": "var(--color-fg-muted)",
      "disabled": "var(--color-fg-disabled)",
      "inverse": "var(--color-fg-inverse)",
      "link": "var(--color-fg-link)",
      "on-action": "var(--color-fg-on-action)",
      "on-danger": "var(--color-fg-on-danger)"
    },
    "border": {
      "default": "var(--color-border-default)",
      "strong": "var(--color-border-strong)"
    },
    "action": {
      "primary": "var(--color-action-primary)",
      "primary-hover": "var(--color-action-primary-hover)",
      "danger": "var(--color-action-danger)",
      "danger-hover": "var(--color-action-danger-hover)"
    },
    "status": {
      "success": {
        "fg": "var(--color-status-success-fg)",
        "bg": "var(--color-status-success-bg)",
        "border": "var(--color-status-success-border)"
      },
      "warning": {
        "fg": "var(--color-status-warning-fg)",
        "bg": "var(--color-status-warning-bg)",
        "border": "var(--color-status-warning-border)"
      },
      "danger": {
        "fg": "var(--color-status-danger-fg)",
        "bg": "var(--color-status-danger-bg)",
        "border": "var(--color-status-danger-border)"
      },
      "info": {
        "fg": "var(--color-status-info-fg)",
        "bg": "var(--color-status-info-bg)",
        "border": "var(--color-status-info-border)"
      },
      "neutral": {
        "fg": "var(--color-status-neutral-fg)",
        "bg": "var(--color-status-neutral-bg)",
        "border": "var(--color-status-neutral-border)"
      }
    },
    "focus": "var(--color-focus)"
  },
  "space": {
    "gap": {
      "2xs": "var(--space-gap-2xs)",
      "xs": "var(--space-gap-xs)",
      "sm": "var(--space-gap-sm)",
      "md": "var(--space-gap-md)",
      "lg": "var(--space-gap-lg)",
      "xl": "var(--space-gap-xl)",
      "2xl": "var(--space-gap-2xl)"
    },
    "inset": {
      "2xs": "var(--space-inset-2xs)",
      "xs": "var(--space-inset-xs)",
      "sm": "var(--space-inset-sm)",
      "md": "var(--space-inset-md)",
      "lg": "var(--space-inset-lg)",
      "xl": "var(--space-inset-xl)"
    },
    "scroll-padding": {
      "start": "var(--space-scroll-padding-start)",
      "end": "var(--space-scroll-padding-end)"
    }
  },
  "size": {
    "control": {
      "sm": "var(--size-control-sm)",
      "md": "var(--size-control-md)",
      "lg": "var(--size-control-lg)"
    },
    "icon": {
      "sm": "var(--size-icon-sm)",
      "md": "var(--size-icon-md)"
    },
    "target-min": "var(--size-target-min)",
    "content": {
      "xs": "var(--size-content-xs)",
      "sm": "var(--size-content-sm)",
      "md": "var(--size-content-md)",
      "lg": "var(--size-content-lg)"
    },
    "sidebar": {
      "sm": "var(--size-sidebar-sm)",
      "md": "var(--size-sidebar-md)",
      "lg": "var(--size-sidebar-lg)"
    },
    "rail": "var(--size-rail)",
    "bar": "var(--size-bar)",
    "grid-item": {
      "sm": "var(--size-grid-item-sm)",
      "md": "var(--size-grid-item-md)",
      "lg": "var(--size-grid-item-lg)"
    },
    "dialog": {
      "sm": "var(--size-dialog-sm)",
      "md": "var(--size-dialog-md)",
      "lg": "var(--size-dialog-lg)"
    },
    "drawer": {
      "sm": "var(--size-drawer-sm)",
      "md": "var(--size-drawer-md)"
    },
    "overlay-max": "var(--size-overlay-max)",
    "scroll-region": {
      "sm": "var(--size-scroll-region-sm)",
      "md": "var(--size-scroll-region-md)",
      "lg": "var(--size-scroll-region-lg)"
    },
    "viewport": {
      "block": "var(--size-viewport-block)"
    },
    "breakpoint": {
      "sm": "var(--size-breakpoint-sm)",
      "md": "var(--size-breakpoint-md)"
    },
    "avatar": {
      "sm": "var(--size-avatar-sm)",
      "md": "var(--size-avatar-md)",
      "lg": "var(--size-avatar-lg)"
    },
    "skeleton": {
      "block": "var(--size-skeleton-block)"
    }
  },
  "radius": {
    "indicator": "var(--radius-indicator)",
    "control": "var(--radius-control)",
    "surface": "var(--radius-surface)",
    "pill": "var(--radius-pill)"
  },
  "font": {
    "family": {
      "body": "var(--font-family-body)",
      "code": "var(--font-family-code)"
    },
    "weight": {
      "body": "var(--font-weight-body)",
      "strong": "var(--font-weight-strong)"
    }
  },
  "border": {
    "width": {
      "default": "var(--border-width-default)"
    }
  },
  "focus": {
    "ring": {
      "width": "var(--focus-ring-width)",
      "offset": "var(--focus-ring-offset)"
    }
  },
  "shadow": {
    "card": "var(--shadow-card)",
    "popover": "var(--shadow-popover)",
    "modal": "var(--shadow-modal)"
  },
  "motion": {
    "fast": "var(--motion-fast)",
    "base": "var(--motion-base)",
    "slow": "var(--motion-slow)",
    "spin": "var(--motion-spin)",
    "pulse": "var(--motion-pulse)"
  },
  "ease": {
    "standard": "var(--ease-standard)",
    "enter": "var(--ease-enter)",
    "exit": "var(--ease-exit)",
    "linear": "var(--ease-linear)"
  },
  "z": {
    "base": "var(--z-base)",
    "sticky": "var(--z-sticky)",
    "dropdown": "var(--z-dropdown)",
    "overlay": "var(--z-overlay)",
    "modal": "var(--z-modal)",
    "toast": "var(--z-toast)",
    "tooltip": "var(--z-tooltip)"
  },
  "icon": {
    "stroke": "var(--icon-stroke)"
  },
  "ratio": {
    "square": "var(--ratio-square)",
    "landscape": "var(--ratio-landscape)",
    "wide": "var(--ratio-wide)"
  },
  "text": {
    "body": "var(--text-body)",
    "body-lg": "var(--text-body-lg)",
    "label": "var(--text-label)",
    "caption": "var(--text-caption)",
    "code": "var(--text-code)",
    "heading-1": "var(--text-heading-1)",
    "heading-2": "var(--text-heading-2)",
    "heading-3": "var(--text-heading-3)",
    "heading-4": "var(--text-heading-4)"
  }
} as const;

export type GapToken = keyof typeof vars.space.gap;
export type InsetToken = keyof typeof vars.space.inset;
export type ContentWidthToken = keyof typeof vars.size.content;
export type SidebarWidthToken = keyof typeof vars.size.sidebar;
export type GridItemToken = keyof typeof vars.size['grid-item'];
export type ScrollRegionToken = keyof typeof vars.size['scroll-region'];
export type RatioToken = keyof typeof vars.ratio;
